### ISSUE TITLE
Testing: Copy Resources module

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/CopyResources#1]
The Copy Resources module allows users to copy selected resources, including items, item sets, sites, and site pages. There are two places a user can copy a resource: 1) from the browse page using the "Copy" icon; and 2) from the resource page using the "Copy" button. Clicking on the icon and button opens up a sidebar where the user confirms the copy. Once the module copies the resource, it automatically navigates to the new resource's page, where the user can make adjustments as needed.

To test this module, copy several items, item sets, sites, and site pages. Check that data does indeed duplicate as expected. Users should be able copy resources that they have permission to create. Copied resources should be owned by the user who copied the resource, not the original owner.

Note that copying an item will not copy its media. If a user must copy an item's media, they can use the [Omeka S Item Importer](https://omeka.org/s/modules/Osii/) module, which already has the ability to copy items along with their media.

Also note that when copying a site, navigation links and page blocks added by modules may carry over as invalid placeholders (stubs). Users will have to replace them or reorganize their navigation and pages. Other data added by modules may not carry over at all.

Even so, modules do have the opportunity to revert their blocks/links and copy their data during the process. Below are the modules that add links, blocks, and/or data to sites:

| Module | Link(s) | Block(s) | Data |
| - | - | - | - |
| Collecting | | X | forms |
| Datavis | X | X | visualizations |
| FacetedBrowse | X | | pages |
| ItemCarouselBlock | | X | |
| Mapping | X | X | |
| Scripto | X | X | |

Currently, each of these modules have a "copy-resources" branch that should copy their data over. Test that this is the case.

**Comment by allanaaa** [comment]
Does this need updating for 4.1? I am only getting "Something went wrong" messages immediately after installing. Or maybe I need to deactivate some other things? 

<img width="984" alt="Screenshot 2024-05-16 at 14 50 48" src="https://github.com/omeka-s-modules/CopyResources/assets/28012148/44af19bb-aac5-4a01-b4ae-1a1221cfd402">
<img width="977" alt="Screenshot 2024-05-16 at 14 51 35" src="https://github.com/omeka-s-modules/CopyResources/assets/28012148/d0e109d8-23a7-416f-8554-4987f911da58">
<img width="970" alt="Screenshot 2024-05-16 at 14 52 46" src="https://github.com/omeka-s-modules/CopyResources/assets/28012148/fc241cff-6822-43f8-8cad-6065a98e2c0d">

**Comment by jimsafley** [comment]
I can't reproduce. It may be another module. Open your browser's dev tools. In the console, you should see an error with a URL. Go to that URL and paste the entire error message here.

**Comment by allanaaa** [comment]
> ParseError
> syntax error, unexpected '|', expecting variable (T_VARIABLE)
> 
> Details:
> 
> ParseError: syntax error, unexpected '|', expecting variable (T_VARIABLE) in /var/www/html/amayer/amayer-s/omeka-s/modules/CopyResources/src/Stdlib/CopyResources.php:327
> Stack trace:
> #0 /var/www/html/amayer/amayer-s/omeka-s/vendor/laminas/laminas-loader/src/StandardAutoloader.php(220): Laminas\Loader\StandardAutoloader->loadClass('CopyResources\\S...', 'namespaces')
> #1 [internal function]: Laminas\Loader\StandardAutoloader->autoload('CopyResources\\S...')
> #2 /var/www/html/amayer/amayer-s/omeka-s/modules/CopyResources/src/Service/Stdlib/CopyResourcesFactory.php(12): spl_autoload_call('CopyResources\\S...')
> #3 /var/www/html/amayer/amayer-s/omeka-s/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(612): CopyResources\Service\Stdlib\CopyResourcesFactory->__invoke(Object(Laminas\ServiceManager\ServiceManager), 'CopyResources\\C...', NULL)
> #4 /var/www/html/amayer/amayer-s/omeka-s/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(234): Laminas\ServiceManager\ServiceManager->doCreate('CopyResources\\C...')
> #5 /var/www/html/amayer/amayer-s/omeka-s/modules/CopyResources/src/Service/Controller/Admin/IndexControllerFactory.php(12): Laminas\ServiceManager\ServiceManager->get('CopyResources\\C...')
> #6 /var/www/html/amayer/amayer-s/omeka-s/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(612): CopyResources\Service\Controller\Admin\IndexControllerFactory->__invoke(Object(Laminas\ServiceManager\ServiceManager), 'CopyResources\\C...', NULL)
> #7 /var/www/html/amayer/amayer-s/omeka-s/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(234): Laminas\ServiceManager\ServiceManager->doCreate('CopyResources\\C...')
> #8 /var/www/html/amayer/amayer-s/omeka-s/vendor/laminas/laminas-servicemanager/src/AbstractPluginManager.php(166): Laminas\ServiceManager\ServiceManager->get('CopyResources\\C...')
> #9 /var/www/html/amayer/amayer-s/omeka-s/vendor/laminas/laminas-mvc/src/DispatchListener.php(96): Laminas\ServiceManager\AbstractPluginManager->get('CopyResources\\C...')
> #10 /var/www/html/amayer/amayer-s/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent))
> #11 /var/www/html/amayer/amayer-s/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
> #12 /var/www/html/amayer/amayer-s/omeka-s/vendor/laminas/laminas-mvc/src/Application.php(325): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
> #13 /var/www/html/amayer/amayer-s/omeka-s/index.php(21): Laminas\Mvc\Application->run()
> #14 {main}
>

**Comment by jimsafley** [comment]
Thanks for finding that. It was a PHP 7 compatibility issue. Pull and try again.

**Comment by allanaaa** [comment]
I just tried to copy a site, and when I clicked confirm, it loaded a page full of this. But it does appear to have successfully copied!:

> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
> 
> Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312

**Comment by allanaaa** [comment]
No probems copying an item or an item set. The same issue happens when I copy a page.

**Comment by allanaaa** [comment]
It appears to be something wrong with that specific site and/or page. Other sites copy with no issue.


https://github.com/omeka-s-modules/CopyResources/assets/28012148/58e7f7b9-df97-47f0-ab2d-e032bd34a639

**Comment by jimsafley** [comment]
There's no other content on the page you see the errors? Is it just a page containing notices?

**Comment by allanaaa** [comment]
Nothing. Just the straight text you can see in the video.

**Comment by jimsafley** [comment]
That indicates that there was a fatal error at some point after those notices. Anything in your `logs/application.log` file that seems relevant? Or your PHP error log?

**Comment by allanaaa** [comment]
I've checked all my logging and run everything a few times, but I can't get any error reporting anywhere.

I had only one page that was giving me the copy error, and I removed blocks until it worked. It appears to be breaking on normal media embed blocks, but with a bunch of attachments that no longer exist:

<img width="782" alt="Screenshot 2024-06-11 at 14 20 26" src="https://github.com/omeka-s-modules/CopyResources/assets/28012148/719efbba-a72d-4aab-9f39-6afde64ce6ee">

I had 10-15 blocks like that, calling items I had deleted. When I deleted some/most (but not all) of them, the copying worked without an error. It may also just be that there were too many blocks on the page and their content doesn't matter. 

That said, now that none of my individual pages are erroring, copying the whole site still produces the same error. 

Again, the copying works fine even when the error comes up, so perhaps you can just route that into a warning or something? I'm not sure how much more help I can be.

**Comment by allanaaa** [comment]
I got an error when trying to rename/reslug a copied site:

<img width="909" alt="Screenshot 2024-06-11 at 15 14 03" src="https://github.com/omeka-s-modules/CopyResources/assets/28012148/fc9ca197-eba4-424d-b631-7903d0ae68b8">

    Invalid navigation: page link missing page ID
    Invalid navigation: invalid link data

I believe it was because I had an empty entry in the nav:

<img width="703" alt="Screenshot 2024-06-11 at 15 17 33" src="https://github.com/omeka-s-modules/CopyResources/assets/28012148/1cf83f43-0090-4a18-aad1-53ec95405321">

**Comment by allanaaa** [comment]
I've never gotten Scripto set up, so I haven't tested that. 

All the other modules you've listed are copying their data fine (as is Metadata Browse, and Sharing).

**Comment by allanaaa** [comment]
My user at the Author level is able to copy items and item sets that they do not own - this is intended, right? So that they can work on the copies without impacting the original? 

<img width="1115" alt="Screenshot 2024-06-11 at 15 52 11" src="https://github.com/omeka-s-modules/CopyResources/assets/28012148/e319b3cb-262c-4c94-983c-95faa556ff07">


Researcher can't copy anything, even items they own. Everyone from Author up can do any resource copying they want. That seems fine in theory. 

My issue with this is, maybe we don't want to automatically add these resources to sites, or maybe not automatically make them public, until someone has a chance to modify them as intended. We don't want a plurality of duplicates immediately visible to the public.

**Comment by allanaaa** [comment]
When it comes to site permissions, site managers can't copy their own sites:

<img width="1131" alt="Screenshot 2024-06-11 at 15 58 40" src="https://github.com/omeka-s-modules/CopyResources/assets/28012148/55e5745c-f336-4b37-ad62-54ff6b4a99af">

When I bumped the user up to Editor, they were able to copy both sites they were Manager on and sites they had no permissions on. 

However, the copying gave some errors:

<img width="1131" alt="Screenshot 2024-06-11 at 15 59 16" src="https://github.com/omeka-s-modules/CopyResources/assets/28012148/5e044052-bb13-4de0-92f9-81b59980db5a">

In this case, Datavis, Mapping, and Collecting don't appear to have copied (and FB isn't visible). Metadata Browse did copy fine. 

So, we might want to remove site and page copying permissions from Editor if that means complications with the modules. I would also be fine with site managers not having copying permissions (for now anyways).

**Comment by jimsafley** [comment]
This notice is puzzling:

```
Notice: Trying to access array offset on value of type null in /var/www/html/amayer/amayer-s/omeka-s/application/src/Api/Adapter/SitePageAdapter.php on line 312
```

It definitely has something to do with the missing attachments, because it indicates that the adapter is receiving an invalid data structure when hydrating the attachments. But, at least on my installation, missing attachments still submit with a valid data structure.

Beyond that, the fact that you're getting a page full of notices and nothing else suggests that there's a fatal error happening somewhere after the notices are raised. Odd that you can't find this error.

I'm puzzled that a) I can't reproduce the error, and b) the copying still works. I'll give it more thought, but I'd hate to delay release just for this.

---

As for this:

```
Invalid navigation: page link missing page ID
Invalid navigation: invalid link data
```

Again, I can't reproduce this. I have missing pages but I'm not getting an error when saving a copied site. Try deleting that link from navigation and rename/reslug the copied site.

At any rate, I don't think this is related to CopyResources and shouldn't affect release.

---

> My user at the Author level is able to copy items and item sets that they do not own - this is intended, right? So that they can work on the copies without impacting the original?

Yes, this is intended for the reason you say.

> Researcher can't copy anything, even items they own. Everyone from Author up can do any resource copying they want. That seems fine in theory.

Researchers can't create their own resources, but I suppose someone can transfer ownership to them. Even so, researchers should not be able to copy anything, even items they own by transfer.

> My issue with this is, maybe we don't want to automatically add these resources to sites, or maybe not automatically make them public, until someone has a chance to modify them as intended. We don't want a plurality of duplicates immediately visible to the public.

Interesting. I'm more inclined to make the copied resources private than I am to remove site assignment. I'll give it some thought.

---

> When it comes to site permissions, site managers can't copy their own sites:

Users with lower roles should not be able to copy sites.

> When I bumped the user up to Editor, they were able to copy both sites they were Manager on and sites they had no permissions on.

This is expected. Editors have special privileges on sites that aren't influenced by site permissions.

> However, the copying gave some errors:

That error will be fixed in the next FacetedBrowse release.

> In this case, Datavis, Mapping, and Collecting don't appear to have copied (and FB isn't visible). Metadata Browse did copy fine.

This is expected. It's an inevitable consequence of every module having separate permissions to their data. 

> So, we might want to remove site and page copying permissions from Editor if that means complications with the modules. I would also be fine with site managers not having copying permissions (for now anyways).

I think editors should be able to copy sites and pages, regardless of complications with modules. It's up to them to remove invalid page blocks and navigation links, and to reconcile invalid or incomplete module data before publishing. In any case, they may just want to preserve the general structure of the site or page, and not care about complications with modules.

**Comment by jimsafley** [comment]
I'm going to close this issue. There's room for more discussion, but I think the module is ready for release, after documentation (see #2).

**Comment by allanaaa** [comment]
> Interesting. I'm more inclined to make the copied resources private than I am to remove site assignment. I'll give it some thought.

Yes, I am definitely starting to think a duplicated resource should be private until the user changes that to public. That goes for sites, pages, items, and item sets.
