### ISSUE TITLE
Testing: Set visibility on copy

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/CopyResources#3]
Per [this discussion](https://github.com/omeka-s-modules/CopyResources/issues/1#issuecomment-2166717867), the [set-visibility-on-copy](https://github.com/omeka-s-modules/CopyResources/compare/main...set-visibility-on-copy) branch adds a way for users to set visibility when copying a resource. Every copy sidebar should now include a "Visibility" select with the following options:

- Same as original: the copied resource will be the same visibility as the original (default)
- Public: the copied resource will be public 
- Private: the copied resource will be private

Make sure this all behaves as expected.

**Comment by allanaaa** [comment]
Works great, thanks! Docs update ASAP.
