### ISSUE TITLE
List of pages block

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-modules/CopyResources#4]
The "list of pages" block doesn't seem to be copying (and may be the source of my bug?). 

It appears to have the same content copied on the editing side:
<img width="643" alt="Screenshot 2024-06-17 at 13 39 02" src="https://github.com/omeka-s-modules/CopyResources/assets/28012148/4ee277a2-b0f8-414f-91ca-0ab08014db39">

But on public:
<img width="477" alt="Screenshot 2024-06-17 at 13 38 03" src="https://github.com/omeka-s-modules/CopyResources/assets/28012148/ce883138-043b-4599-b397-3e19491f8db8">

(The original, for reference:)
<img width="496" alt="Screenshot 2024-06-17 at 13 37 59" src="https://github.com/omeka-s-modules/CopyResources/assets/28012148/6c6a5172-c567-4225-a812-6060766e270f">

**Comment by jimsafley** [comment]
Good catch. Yes, I see it too. This happens because the module sets the block data before creating the page copies. As a result, the block data contains invalid page IDs (i.e. the original page IDs), which is why you're seeing the missing pages. It's fixable but tricky. It may have to wait until after release.

**Comment by allanaaa** [comment]
Sure. I can put it in the "known issues" section in the docs for now, if you want to go without it.

**Comment by jimsafley** [comment]
Put it in "known issues". The fix will take too long to justify any more delay.

**Comment by allanaaa** [comment]
Done!

**Comment by jimsafley** [comment]
The [fix-list-of-pages-block](https://github.com/omeka-s-modules/CopyResources/compare/main...fix-list-of-pages-block) branch should correctly copy "List of pages" blocks. The best way to test this is to create several "List of pages" blocks, each with a complex page hierarchy. They all should preserve the hierarchy and show links to valid pages within the copied site.

**Comment by allanaaa** [comment]
This is working! Tragically, it does not appear to be solving my weird site-copy bug. I'll update that part of the docs if you're ready to merge this.
